import { describe, expect, it } from "vitest";
import type { Address, Hex } from "viem";
import { getAddress } from "viem";

import vectors from "./vectors/identity.json" with { type: "json" };
import {
  agentIdFor,
  commitmentFor,
  predictAgentLaunch,
  type MarketExpectation,
} from "./identity.js";
import { saltFor } from "../launch/salt.js";

/**
 * The SDK half of the differential harness for an agent's identity.
 *
 * `packages/contracts/test/agents/AgentIdentity.vectors.t.sol` asserts the same
 * expected values against the contracts. Neither implementation may be adjusted to
 * satisfy these vectors: they were generated by padding every field to a word by
 * hand, so they encode the field order and the widths independently of both viem
 * and Solidity.
 *
 * A vector suite of single cases cannot catch an encoding that drops a field — each
 * case would still match its own recorded hash. The mutation pairs can, which is
 * why they are here rather than only in the generator.
 */

const NATIVE: Address = "0x0000000000000000000000000000000000000000";

describe("agentIdFor", () => {
  it("matches every vector", () => {
    for (let i = 0; i < vectors.agentIdCount; i++) {
      const actual = agentIdFor({
        // As a bigint, so the maximum-value case is exercised here too. `Number()`
        // on a 78-digit string rounds *up* past the uint256 ceiling, which is a
        // silent way to skip the one case the corpus has for the widest field.
        chainId: BigInt(vectors.agentIdChainId[i] as string),
        identityRegistry: vectors.agentIdRegistry[i] as Address,
        developer: vectors.agentIdDeveloper[i] as Address,
        salt: vectors.agentIdSalt[i] as Hex,
      });

      expect(actual, `case ${i}`).toBe(vectors.agentIdExpected[i]);
    }
  });

  it("covers the whole of both widths, including the degenerate case", () => {
    // Vector 0 is every field at zero and vector 1 is every field at its maximum.
    // Named here because the corpus is otherwise opaque, and because a suite that
    // never exercises the boundaries is a suite that passes on a truncating cast.
    expect(vectors.agentIdChainId[0]).toBe("0");
    expect(vectors.agentIdChainId[1]).toBe(
      ((1n << 256n) - 1n).toString(),
      "the maximum-value case is not at index 1",
    );
  });

  it("is a pure function of its inputs", () => {
    const input = {
      chainId: 4663,
      identityRegistry: "0x1111111111111111111111111111111111111111" as Address,
      developer: "0x2222222222222222222222222222222222222222" as Address,
      salt: `0x${"ab".repeat(32)}` as Hex,
    };

    expect(agentIdFor(input)).toBe(agentIdFor(input));
  });

  it("does not normalise a checksummed address into a different id", () => {
    // viem lowercases when encoding, so the two forms must agree. If they did not,
    // an interface that displayed a checksummed address and hashed what it
    // displayed would predict an id the chain never assigns. The checksummed form
    // comes from `getAddress` rather than being typed out, because viem rejects a
    // mixed-case address whose checksum is merely plausible.
    const lower = "0xabcdefabcdefabcdefabcdefabcdefabcdefabcd" as Address;
    const checksummed = getAddress(lower);

    expect(checksummed, "the two forms are not actually different").not.toBe(
      lower,
    );

    const base = {
      chainId: 4663,
      identityRegistry: lower,
      salt: `0x${"00".repeat(32)}` as Hex,
    };

    expect(agentIdFor({ ...base, developer: checksummed })).toBe(
      agentIdFor({ ...base, developer: lower }),
    );
  });

  it("separates developers, salts, registries and chains", () => {
    const salt = `0x${"11".repeat(32)}` as Hex;
    const a = "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" as Address;
    const b = "0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb" as Address;

    const base = { chainId: 4663, identityRegistry: a, developer: a, salt };

    // Each of the four fields, changed alone, must move the id. These are the two
    // namespace separations the preimage exists to provide, plus replay protection.
    const ids = new Set([
      agentIdFor(base),
      agentIdFor({ ...base, developer: b }),
      agentIdFor({ ...base, salt: `0x${"22".repeat(32)}` }),
      agentIdFor({ ...base, identityRegistry: b }),
      agentIdFor({ ...base, chainId: 46630 }),
    ]);

    expect(ids.size, "a field is not reaching the preimage").toBe(5);
  });
});

describe("commitmentFor", () => {
  function caseAt(i: number) {
    return {
      chainId: Number(vectors.commitmentChainId[i]),
      identityRegistry: vectors.commitmentIdentityRegistry[i] as Address,
      marketRegistry: vectors.commitmentMarketRegistry[i] as Address,
      developer: vectors.commitmentDeveloper[i] as Address,
      router: vectors.commitmentRouter[i] as Address,
      expectation: {
        token: vectors.commitmentToken[i] as Address,
        quoteAsset: vectors.commitmentQuoteAsset[i] as Address,
        model: vectors.commitmentModel[i] as number,
        expectedSupply: BigInt(vectors.commitmentExpectedSupply[i] as string),
        launchNonce: BigInt(vectors.commitmentLaunchNonce[i] as string),
      } satisfies MarketExpectation,
    };
  }

  it("matches every vector", () => {
    for (let i = 0; i < vectors.commitmentCount; i++) {
      // The maximum case has chainId 2^256-1, which `Number()` cannot hold. It is
      // exercised on the Solidity side and through the bigint path below; here the
      // JS-representable cases are what a caller can actually pass.
      const chainId = BigInt(vectors.commitmentChainId[i] as string);
      if (chainId > BigInt(Number.MAX_SAFE_INTEGER)) continue;

      expect(commitmentFor(caseAt(i)), `case ${i}`).toBe(
        vectors.commitmentExpected[i],
      );
    }
  });

  it("moves when any single field moves", () => {
    // The property no single-case vector can establish. If `router` were left out
    // of the preimage, every one-case assertion above would still pass.
    for (let m = 0; m < vectors.commitmentMutationCount; m++) {
      const field = vectors.commitmentMutationField[m] as string;
      const a = vectors.commitmentMutationA[m] as number;
      const b = vectors.commitmentMutationB[m] as number;

      expect(
        vectors.commitmentExpected[a],
        `changing ${field} did not change the commitment`,
      ).not.toBe(vectors.commitmentExpected[b]);

      expect(commitmentFor(caseAt(a)), `mutation ${field}, side a`).toBe(
        vectors.commitmentExpected[a],
      );
      expect(commitmentFor(caseAt(b)), `mutation ${field}, side b`).toBe(
        vectors.commitmentExpected[b],
      );
    }
  });

  it("refuses a field the contract's own types could not hold", () => {
    const ok = caseAt(2);

    for (const [label, expectation] of [
      ["model above uint8", { ...ok.expectation, model: 256 }],
      ["negative model", { ...ok.expectation, model: -1 }],
      ["fractional model", { ...ok.expectation, model: 1.5 }],
      ["launchNonce above uint64", { ...ok.expectation, launchNonce: 1n << 64n }],
      ["negative supply", { ...ok.expectation, expectedSupply: -1n }],
      ["supply above uint256", { ...ok.expectation, expectedSupply: 1n << 256n }],
    ] as const) {
      expect(
        () => commitmentFor({ ...ok, expectation }),
        label,
      ).toThrow(RangeError);
    }
  });

  it("is a pure function of its inputs", () => {
    const input = caseAt(3);
    expect(commitmentFor(input)).toBe(commitmentFor(input));
  });
});

describe("predictAgentLaunch", () => {
  const deployer = "0xdddddddddddddddddddddddddddddddddddddddd" as Address;
  const developer = "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee" as Address;
  const identityRegistry = "0x1111111111111111111111111111111111111111" as Address;
  const marketRegistry = "0x2222222222222222222222222222222222222222" as Address;
  const router = "0x3333333333333333333333333333333333333333" as Address;
  const initCodeHash = `0x${"cd".repeat(32)}` as Hex;

  const base = {
    chainId: 4663,
    identityRegistry,
    marketRegistry,
    developer,
    agentSalt: `0x${"01".repeat(32)}` as Hex,
    marketSalt: `0x${"02".repeat(32)}` as Hex,
    expectation: {
      quoteAsset: NATIVE,
      model: 0,
      expectedSupply: 1_000_000_000n * 10n ** 18n,
      launchNonce: 1n,
    },
  };

  it("gives the agent id from the agent salt and the token from the market salt", () => {
    const predicted = predictAgentLaunch({
      ...base,
      router,
      deployer,
      tokenInitCodeHash: initCodeHash,
    });

    expect(predicted.agentId).toBe(
      agentIdFor({
        chainId: 4663,
        identityRegistry,
        developer,
        salt: base.agentSalt,
      }),
    );

    // The market salt goes through the factory's namespacing, exactly as an
    // ordinary launch does. Nothing about an agent changes that step.
    expect(predicted.marketSalt).toBe(saltFor(developer, base.marketSalt));
    expect(predicted.token).toMatch(/^0x[0-9a-fA-F]{40}$/);

    expect(predicted.commitment).toBe(
      commitmentFor({
        chainId: 4663,
        identityRegistry,
        marketRegistry,
        developer,
        router,
        expectation: { ...base.expectation, token: predicted.token as Address },
      }),
    );
  });

  it("does not confuse the two salts", () => {
    // They are separate values with separate hashing paths. Swapping them produces
    // a commitment nothing can satisfy, so the two must not collapse into one.
    const swapped = predictAgentLaunch({
      ...base,
      agentSalt: base.marketSalt,
      marketSalt: base.agentSalt,
      router,
      deployer,
      tokenInitCodeHash: initCodeHash,
    });

    const straight = predictAgentLaunch({
      ...base,
      router,
      deployer,
      tokenInitCodeHash: initCodeHash,
    });

    expect(swapped.agentId).not.toBe(straight.agentId);
    expect(swapped.token).not.toBe(straight.token);
  });

  it("answers with the agent id alone before the router exists", () => {
    // The real sequence: an interface knows the agent id and the token address
    // before `createAgent`, and the router only after it. Reporting `undefined` is
    // the honest answer rather than a placeholder that would hash into something.
    const early = predictAgentLaunch({
      ...base,
      deployer,
      tokenInitCodeHash: initCodeHash,
    });

    expect(early.agentId).toBeDefined();
    expect(early.token).toBeDefined();
    expect(early.commitment).toBeUndefined();
  });

  it("omits the token and the commitment when the token cannot be derived", () => {
    const withoutDeployer = predictAgentLaunch({ ...base, router });

    expect(withoutDeployer.agentId).toBeDefined();
    expect(withoutDeployer.token).toBeUndefined();
    expect(withoutDeployer.commitment).toBeUndefined();
  });

  it("accepts a token supplied directly instead of derived", () => {
    const token = "0x4444444444444444444444444444444444444444" as Address;

    const supplied = predictAgentLaunch({
      ...base,
      router,
      expectation: { ...base.expectation, token },
    });

    expect(supplied.token).toBe(token);
    expect(supplied.commitment).toBe(
      commitmentFor({
        chainId: 4663,
        identityRegistry,
        marketRegistry,
        developer,
        router,
        expectation: { ...base.expectation, token },
      }),
    );
  });

  it("is deterministic across repeated calls", () => {
    const input = {
      ...base,
      router,
      deployer,
      tokenInitCodeHash: initCodeHash,
    };

    expect(predictAgentLaunch(input)).toEqual(predictAgentLaunch(input));
  });
});
