/**
 * An agent's id, and the commitment that binds it to a market.
 *
 * The twin of `AgentIdentityRegistry.agentIdFor` and its private `_commitment`.
 * Both are `keccak256` over an `abi.encode`, so mirroring them is a matter of
 * getting ten fields, their order and their widths exactly right — and getting
 * one wrong produces a plausible 32-byte value that simply never matches.
 *
 * ## Why an interface needs these at all
 *
 * Because an Agen launch is three transactions and the middle one cannot be
 * corrected. The developer creates an agent that commits to a market that does not
 * exist yet, then launches that market, then binds them. If the commitment made in
 * step one does not describe what step two produced, step three reverts forever:
 * `bindMarket` is the only path to `MarketBound` and an agent stuck in `Created`
 * can never be activated.
 *
 * So the interface has to be able to say, before the first signature, "this is the
 * token address your launch will produce and this is the commitment your agent will
 * hold" — and be right. `predictAgentLaunch` is that answer.
 *
 * ## What the preimages contain, and why
 *
 * Both mix in the chain id and the registry's own address, so neither an id nor a
 * commitment is portable between chains or between two deployments of the same
 * registry. `agentIdFor` mixes in the developer, so choosing a salt cannot reach
 * into somebody else's namespace — the same reasoning as `VerdantFactory.saltFor`.
 * The commitment mixes in the router, because the router is what makes the market
 * pay this agent, and the market registry, because a commitment is a claim about a
 * market in one particular registry.
 *
 * ## The authority
 *
 * `src/agents/vectors/identity.json` holds a corpus generated by hand-rolled word
 * padding — not by the `encodeAbiParameters` this file calls, and not by Solidity's
 * `abi.encode`. `identity.test.ts` holds this file to it and
 * `test/agents/AgentIdentity.vectors.t.sol` holds the contracts to it, so three
 * independent encodings have to agree before either side is believed.
 */

import type { Address, Hex } from "viem";
import { encodeAbiParameters, getCreate2Address, keccak256 } from "viem";

import { saltFor } from "../launch/salt.js";

/**
 * What an agent commits to about the market it has not launched yet.
 *
 * The twin of `IAgentIdentityRegistry.MarketExpectation`. The widths are the
 * contract's: `model` is a `uint8` and `launchNonce` a `uint64`, and both are
 * padded to a word by `abi.encode`. They are `number` here rather than `bigint`
 * because neither can exceed what a JavaScript integer holds exactly, and asking a
 * caller for `0n` where the contract's own tests write `0` invites a mismatch of
 * its own.
 */
export interface MarketExpectation {
  /** The launch token, predicted from the mined salt. */
  readonly token: Address;
  /** The pool's `currency0`: ether, or the equity the market is quoted in. */
  readonly quoteAsset: Address;
  /** Index into `ModelRegistry`'s models. `uint8` on chain. */
  readonly model: number;
  /** Total supply, in the token's own units. */
  readonly expectedSupply: bigint;
  /**
   * The developer's own discriminant, so one developer can hold two
   * otherwise-identical expectations without them colliding. `uint64` on chain.
   */
  readonly launchNonce: bigint;
}

/**
 * The chain id, as either form.
 *
 * `bigint` is accepted because the preimage's field is a `uint256` and a real chain
 * id is a `number`. Requiring `number` would make the wide half of the field
 * unreachable and untestable; requiring `bigint` would make every ordinary call
 * write `4663n`. Both are normalised on the way in.
 */
export type ChainId = number | bigint;

/** The deployment addresses the two preimages are anchored to. */
export interface AgentRegistryAnchor {
  /** `AgentIdentityRegistry`. In both preimages as `address(this)`. */
  readonly identityRegistry: Address;
  /** `MarketRegistry`. In the commitment only. */
  readonly marketRegistry: Address;
  /** The chain the registry is deployed on. */
  readonly chainId: ChainId;
}

const MAX_UINT8 = 255n;
const MAX_UINT64 = (1n << 64n) - 1n;
const MAX_UINT256 = (1n << 256n) - 1n;

/**
 * `AgentIdentityRegistry.agentIdFor`.
 *
 * `keccak256(abi.encode(block.chainid, address(this), developer, salt))`.
 *
 * `salt` is the developer's chosen value, unmodified — unlike a market launch,
 * where the factory namespaces the salt before using it. The registry mixes the
 * developer in here instead, which achieves the same thing one level up.
 */
export function agentIdFor({
  chainId,
  identityRegistry,
  developer,
  salt,
}: {
  readonly chainId: ChainId;
  readonly identityRegistry: Address;
  readonly developer: Address;
  readonly salt: Hex;
}): Hex {
  return keccak256(
    encodeAbiParameters(
      [
        { type: "uint256" },
        { type: "address" },
        { type: "address" },
        { type: "bytes32" },
      ],
      [BigInt(chainId), identityRegistry, developer, salt],
    ),
  );
}

/**
 * `AgentIdentityRegistry.commitmentFor`.
 *
 * Ten fields, in the contract's order, which is deliberately *not* the order of
 * `MarketExpectation`'s own fields: the router sits between `model` and
 * `expectedSupply`. Restating the order here rather than spreading the struct is
 * what makes that visible.
 */
export function commitmentFor({
  chainId,
  identityRegistry,
  marketRegistry,
  developer,
  router,
  expectation,
}: AgentRegistryAnchor & {
  readonly developer: Address;
  /** The agent's `AgentRevenueRouter`, which the market must pay. */
  readonly router: Address;
  readonly expectation: MarketExpectation;
}): Hex {
  requireEncodableExpectation(expectation);

  return keccak256(
    encodeAbiParameters(
      [
        { type: "uint256" }, // block.chainid
        { type: "address" }, // address(this)
        { type: "address" }, // address(markets)
        { type: "address" }, // developer
        { type: "address" }, // expectation.token
        { type: "address" }, // expectation.quoteAsset
        { type: "uint8" }, //   expectation.model
        { type: "address" }, // router
        { type: "uint256" }, // expectation.expectedSupply
        { type: "uint64" }, //  expectation.launchNonce
      ],
      [
        BigInt(chainId),
        identityRegistry,
        marketRegistry,
        developer,
        expectation.token,
        expectation.quoteAsset,
        expectation.model,
        router,
        expectation.expectedSupply,
        expectation.launchNonce,
      ],
    ),
  );
}

/**
 * Refuses a field the contract's own types could not hold.
 *
 * `encodeAbiParameters` would refuse most of these too, but the message would
 * describe an ABI type rather than the launch parameter the caller actually set,
 * and this is the boundary where a wizard's numeric input arrives.
 */
function requireEncodableExpectation(expectation: MarketExpectation): void {
  const model = BigInt(expectation.model);
  if (!Number.isInteger(expectation.model) || model < 0n || model > MAX_UINT8) {
    throw new RangeError(
      `model must be a uint8 (0..255); received ${expectation.model}`,
    );
  }
  if (expectation.launchNonce < 0n || expectation.launchNonce > MAX_UINT64) {
    throw new RangeError(
      `launchNonce must be a uint64; received ${expectation.launchNonce}`,
    );
  }
  if (expectation.expectedSupply < 0n || expectation.expectedSupply > MAX_UINT256) {
    throw new RangeError(
      `expectedSupply must be a uint256; received ${expectation.expectedSupply}`,
    );
  }
}

// --- the whole launch, predicted ------------------------------------------

/**
 * Everything about an Agen launch that is knowable before any of it happens.
 *
 * `token` is `undefined` when the caller did not supply the deployer and init code
 * hash needed to derive it. That is the honest answer rather than a guess — but it
 * also means `commitment` cannot be computed, because the token address is one of
 * the ten fields hashed into it. The two travel together for that reason.
 */
export interface PredictedAgentLaunch {
  /** The id the agent will be registered under. */
  readonly agentId: Hex;
  /** The commitment the agent will hold, if the token address is known. */
  readonly commitment: Hex | undefined;
  /** Where `VerdantDeployer` will create the token, if predictable. */
  readonly token: Address | undefined;
  /** The namespaced salt the market's contracts are created with. */
  readonly marketSalt: Hex;
}

/**
 * The agent id, the token address and the commitment, from the inputs a launch
 * form holds.
 *
 * Two salts are in play and they are not interchangeable, which is the thing this
 * function exists to stop a caller getting wrong:
 *
 *  - `agentSalt` is hashed with the developer by the *registry* to make the agent
 *    id. It is the developer's namespace within Agen.
 *  - `marketSalt` is hashed with the creator by the *factory* (`saltFor`) to make
 *    the CREATE2 salt every one of the market's contracts is deployed under. It is
 *    what a caller mines with `mineTokenSalt` to put the token above the quote
 *    asset.
 *
 * They may hold the same value and usually will, because a developer launching one
 * market per agent has no reason to separate them. Passing one where the other
 * belongs produces a commitment that cannot be satisfied, so they are named
 * distinctly and neither defaults to the other.
 *
 * `router` is required for the commitment because the registry hashes it. Its
 * address is not predictable — `AgentDeployer` uses plain `CREATE`, deliberately —
 * so in practice a caller computes the commitment *after* `createAgent` has
 * returned the router, and computes the token address and agent id before it. Both
 * halves are available here so an interface can show the first two immediately and
 * fill the third in when it has it.
 */
export function predictAgentLaunch({
  chainId,
  identityRegistry,
  marketRegistry,
  developer,
  agentSalt,
  marketSalt,
  router,
  expectation,
  deployer,
  tokenInitCodeHash,
}: AgentRegistryAnchor & {
  readonly developer: Address;
  /** The developer's chosen value, hashed by the registry into the agent id. */
  readonly agentSalt: Hex;
  /** The developer's chosen value, hashed by the factory into the CREATE2 salt. */
  readonly marketSalt: Hex;
  /** The agent's revenue router, once known. Omit before `createAgent`. */
  readonly router?: Address | undefined;
  /**
   * The expectation, with `token` optional: it is derived here when `deployer` and
   * `tokenInitCodeHash` are given, and required otherwise.
   */
  readonly expectation: Omit<MarketExpectation, "token"> & {
    readonly token?: Address | undefined;
  };
  /** `VerdantDeployer`, which performs the token's CREATE2. */
  readonly deployer?: Address | undefined;
  /** From `readTokenInitCodeHash`. Comes from the chain; not hardcodable. */
  readonly tokenInitCodeHash?: Hex | undefined;
}): PredictedAgentLaunch {
  const agentId = agentIdFor({
    chainId,
    identityRegistry,
    developer,
    salt: agentSalt,
  });

  const token =
    expectation.token ??
    (deployer !== undefined && tokenInitCodeHash !== undefined
      ? getCreate2Address({
          from: deployer,
          salt: saltFor(developer, marketSalt),
          bytecodeHash: tokenInitCodeHash,
        })
      : undefined);

  const commitment =
    token !== undefined && router !== undefined
      ? commitmentFor({
          chainId,
          identityRegistry,
          marketRegistry,
          developer,
          router,
          expectation: { ...expectation, token },
        })
      : undefined;

  return {
    agentId,
    commitment,
    token,
    marketSalt: saltFor(developer, marketSalt),
  };
}
