import { describe, expect, it } from "vitest";
import type { Address, Hex } from "viem";
import { getAddress, keccak256, toHex } from "viem";

import vectors from "./vectors/identity.json" with { type: "json" };
import {
  SERVICE_QUOTE_TYPE,
  SERVICE_QUOTE_TYPEHASH,
  hashServiceQuote,
  serviceQuoteSigningDigest,
  type ServiceQuote,
} from "./quote.js";

/**
 * The SDK half of the differential harness for a service quote's hash.
 *
 * The vectors were generated by writing each word out by hand, so they encode the
 * field order and the widths independently of viem's `encodeAbiParameters` and of
 * Solidity's `abi.encode`. `AgentIdentity.vectors.t.sol` asserts the same values
 * against `AgentActionLib.hash`.
 */

describe("the typehash", () => {
  it("matches the vector, which was hashed from the type string as raw bytes", () => {
    expect(SERVICE_QUOTE_TYPEHASH).toBe(vectors.serviceQuoteTypehash);
  });

  it("uses the exact type string the contract declares", () => {
    // Byte-identical, including the absence of spaces after commas. One space would
    // change the typehash and therefore every quote hash ever computed.
    expect(SERVICE_QUOTE_TYPE).toBe(vectors.serviceQuoteType);
    expect(SERVICE_QUOTE_TYPEHASH).toBe(keccak256(toHex(SERVICE_QUOTE_TYPE)));
  });

  it("names the ten fields in the struct's order", () => {
    const fields = SERVICE_QUOTE_TYPE.slice(
      SERVICE_QUOTE_TYPE.indexOf("(") + 1,
      -1,
    )
      .split(",")
      .map((entry) => entry.split(" ")[1]);

    expect(fields).toEqual([
      "agentId",
      "providerAgentId",
      "serviceId",
      "serviceVersion",
      "provider",
      "asset",
      "exactAmount",
      "requestId",
      "deadline",
      "nonce",
    ]);
  });
});

describe("hashServiceQuote", () => {
  function caseAt(i: number): ServiceQuote {
    return {
      agentId: vectors.quoteAgentId[i] as Hex,
      providerAgentId: vectors.quoteProviderAgentId[i] as Hex,
      serviceId: vectors.quoteServiceId[i] as Hex,
      serviceVersion: vectors.quoteServiceVersion[i] as number,
      provider: vectors.quoteProvider[i] as Address,
      asset: vectors.quoteAsset[i] as Address,
      exactAmount: BigInt(vectors.quoteExactAmount[i] as string),
      requestId: vectors.quoteRequestId[i] as Hex,
      deadline: BigInt(vectors.quoteDeadline[i] as string),
      nonce: BigInt(vectors.quoteNonce[i] as string),
    };
  }

  it("matches every vector", () => {
    for (let i = 0; i < vectors.quoteCount; i++) {
      expect(hashServiceQuote(caseAt(i)), `case ${i}`).toBe(
        vectors.quoteExpected[i],
      );
    }
  });

  it("covers zero and the maximum of every width", () => {
    // Index 0 is every field at zero; index 1 is every field at its maximum,
    // including a uint32 serviceVersion at 2^32-1 and three uint256 at 2^256-1.
    expect(vectors.quoteServiceVersion[1]).toBe(Number((1n << 32n) - 1n));
    expect(vectors.quoteExactAmount[1]).toBe(((1n << 256n) - 1n).toString());
  });

  it("moves when any single field moves", () => {
    // The property a suite of independent cases cannot establish: an encoding that
    // dropped `requestId` would match every single-case vector above.
    for (let m = 0; m < vectors.quoteMutationCount; m++) {
      const field = vectors.quoteMutationField[m] as string;
      const a = vectors.quoteMutationA[m] as number;
      const b = vectors.quoteMutationB[m] as number;

      expect(
        hashServiceQuote(caseAt(a)),
        `changing ${field} did not change the hash`,
      ).not.toBe(hashServiceQuote(caseAt(b)));
    }
  });

  it("is a pure function of its inputs", () => {
    const quote = caseAt(5);
    expect(hashServiceQuote(quote)).toBe(hashServiceQuote(quote));
  });

  it("treats a checksummed address as the address it is", () => {
    const quote = caseAt(5);
    const lower = "0xabcdefabcdefabcdefabcdefabcdefabcdefabcd" as Address;
    const checksummed = getAddress(lower);

    expect(checksummed).not.toBe(lower);
    expect(hashServiceQuote({ ...quote, provider: checksummed })).toBe(
      hashServiceQuote({ ...quote, provider: lower }),
    );
  });

  it("refuses a field the contract's own types could not hold", () => {
    const quote = caseAt(5);

    for (const [label, edit] of [
      ["serviceVersion above uint32", { serviceVersion: Number(1n << 32n) }],
      ["negative serviceVersion", { serviceVersion: -1 }],
      ["fractional serviceVersion", { serviceVersion: 1.5 }],
      ["exactAmount above uint256", { exactAmount: 1n << 256n }],
      ["negative exactAmount", { exactAmount: -1n }],
      ["deadline above uint256", { deadline: 1n << 256n }],
      ["nonce above uint256", { nonce: 1n << 256n }],
    ] as const) {
      expect(() => hashServiceQuote({ ...quote, ...edit }), label).toThrow(
        RangeError,
      );
    }
  });
});

describe("serviceQuoteSigningDigest", () => {
  it("is the EIP-712 envelope around the struct hash, not the struct hash", () => {
    // The distinction that matters: the bare struct hash has no domain separator,
    // so signing it would produce a signature replayable on every chain and every
    // deployment. Nothing verifies this today; it exists so that when session keys
    // arrive the safe construction is already the one available.
    const quote: ServiceQuote = {
      agentId: `0x${"11".repeat(32)}`,
      providerAgentId: `0x${"22".repeat(32)}`,
      serviceId: `0x${"33".repeat(32)}`,
      serviceVersion: 1,
      provider: "0x4444444444444444444444444444444444444444",
      asset: "0x0000000000000000000000000000000000000000",
      exactAmount: 10n ** 17n,
      requestId: `0x${"55".repeat(32)}`,
      deadline: 1_800_000_000n,
      nonce: 0n,
    };

    const domain = `0x${"ab".repeat(32)}` as Hex;
    const digest = serviceQuoteSigningDigest(domain, quote);

    expect(digest).not.toBe(hashServiceQuote(quote));
    expect(digest).toBe(
      keccak256(
        `0x1901${domain.slice(2)}${hashServiceQuote(quote).slice(2)}`,
      ),
    );

    // A different domain must give a different digest, which is the whole reason
    // the domain is in there.
    expect(serviceQuoteSigningDigest(`0x${"cd".repeat(32)}`, quote)).not.toBe(
      digest,
    );
  });
});
