// SPDX-License-Identifier: BUSL-1.1
pragma solidity 0.8.26;

import {Test} from "forge-std/Test.sol";
import {Currency} from "@uniswap/v4-core/src/types/Currency.sol";
import {IHooks} from "@uniswap/v4-core/src/interfaces/IHooks.sol";
import {PoolKey} from "@uniswap/v4-core/src/types/PoolKey.sol";
import {IV4Router} from "@uniswap/v4-periphery/src/interfaces/IV4Router.sol";
import {Actions} from "@uniswap/v4-periphery/src/libraries/Actions.sol";

/// @notice The one function of the Universal Router the SDK encodes for.
/// @dev Restated rather than vendored: `universal-router` is not among the pinned
/// dependencies, and adding a repository to obtain one signature would cost more than
/// writing it. The signature is stable across every router version that supports v4.
interface IUniversalRouter {
    function execute(bytes calldata commands, bytes[] calldata inputs, uint256 deadline) external payable;
}

/// @title Differential vector harness for a swap's calldata — Solidity half
///
/// @notice Asserts that the bytes `trade.buildSwap` produces in
/// `packages/sdk/src/trade/swap.ts` are the bytes Uniswap's own action constants and
/// parameter layout produce for the same trade.
///
/// @dev This exists because the swap builder is the one part of the write path with
/// nowhere to run. A launch can be broadcast to a local anvil and checked — and since
/// `apps/web/scripts/assert-sdk-launch.ts` it is, on every `pnpm proof` — but a swap
/// goes through the Universal Router, which is not deployed on any local rig and
/// cannot be: its source is not vendored, and fetching either the repository or its
/// deployed bytecode needs a network that the offline gates do not have.
///
/// So the guarantee is split in two, and this file is the half that runs offline:
///
///   1. **The bytes are right.** Here. Every case is rebuilt from
///      `Actions.SWAP_EXACT_IN_SINGLE` and its two siblings, from
///      `IV4Router.ExactInputSingleParams`, and from the `execute` signature — the
///      vendored source rather than a transcription of it — and must equal the SDK's
///      output to the byte.
///   2. **The deployed router accepts bytes of that shape.**
///      `test_aThirdPartyRouterChargesTheScheduledFee` in `test/fork/Launch.fork.t.sol`,
///      against the real router on 4663. That one needs the network, so it runs under
///      `bash scripts/fork-test.sh`, which warns rather than fails when the RPC is
///      unreachable.
///
/// Neither half is sufficient. This one cannot catch a wrong `V4_SWAP` command byte,
/// because the command byte is the one constant with no vendored source to check it
/// against — that is what the fork run is for.
///
/// The corpus is generated by `pnpm vectors:generate:swap` in packages/sdk and is
/// committed, so regenerating it after a change to the builder is a visible diff
/// rather than a silent one.
contract SwapCalldataVectorsTest is Test {
    string internal constant VECTORS = "../sdk/src/models/vectors/swap.json";

    /// @dev `Commands.V4_SWAP`. The one value here with no vendored source behind it,
    /// for the reason the SDK's own comment gives: `universal-router` is not a pinned
    /// dependency, so there is no `Commands.sol` to read it from. Both this and the
    /// SDK's copy are checked by the fork test, which reverts on a wrong command.
    uint8 internal constant V4_SWAP = 0x10;

    struct Corpus {
        uint256 count;
        uint256 tickSpacing;
        uint256 fee;
        address router;
        address hook;
        string[] names;
        address[] currency0s;
        address[] currency1s;
        bool[] zeroForOnes;
        string[] amountIns;
        string[] minAmountOuts;
        string[] deadlines;
        bytes[] calldatas;
    }

    function _load() internal view returns (Corpus memory c) {
        string memory json = vm.readFile(VECTORS);

        c.count = vm.parseJsonUint(json, ".count");
        c.tickSpacing = vm.parseJsonUint(json, ".tickSpacing");
        c.fee = vm.parseJsonUint(json, ".fee");
        c.router = vm.parseJsonAddress(json, ".router");
        c.hook = vm.parseJsonAddress(json, ".hook");
        c.names = vm.parseJsonStringArray(json, ".names");
        c.currency0s = vm.parseJsonAddressArray(json, ".currency0s");
        c.currency1s = vm.parseJsonAddressArray(json, ".currency1s");
        c.zeroForOnes = vm.parseJsonBoolArray(json, ".zeroForOnes");
        // Decimal strings, parsed here. `type(uint256).max` is one of the deadlines and
        // JSON has no integer that wide, so a number in the document would either
        // overflow or arrive as a float that had quietly lost its low bits.
        c.amountIns = vm.parseJsonStringArray(json, ".amountIns");
        c.minAmountOuts = vm.parseJsonStringArray(json, ".minAmountOuts");
        c.deadlines = vm.parseJsonStringArray(json, ".deadlines");
        c.calldatas = vm.parseJsonBytesArray(json, ".calldatas");
    }

    function _key(Corpus memory c, uint256 i) internal pure returns (PoolKey memory) {
        return PoolKey({
            currency0: Currency.wrap(c.currency0s[i]),
            currency1: Currency.wrap(c.currency1s[i]),
            // forge-lint: disable-next-line(unsafe-typecast) -- the corpus pins the flag
            fee: uint24(c.fee),
            // forge-lint: disable-next-line(unsafe-typecast) -- the corpus pins 200
            tickSpacing: int24(uint24(c.tickSpacing)),
            hooks: IHooks(c.hook)
        });
    }

    /// @dev One `V4_SWAP` command carrying three actions: do the swap, pay the input,
    /// take the output. `SETTLE_ALL` names the currency being spent and `TAKE_ALL` the
    /// one being received, which is the pair a sell exchanges — and the reason the
    /// corpus contains one.
    function _encode(
        address router,
        PoolKey memory key,
        bool zeroForOne,
        uint256 amountIn,
        uint256 minAmountOut,
        uint256 deadline
    ) internal pure returns (bytes memory) {
        Currency currencyIn = zeroForOne ? key.currency0 : key.currency1;
        Currency currencyOut = zeroForOne ? key.currency1 : key.currency0;

        bytes memory actions =
            abi.encodePacked(uint8(Actions.SWAP_EXACT_IN_SINGLE), uint8(Actions.SETTLE_ALL), uint8(Actions.TAKE_ALL));

        bytes[] memory params = new bytes[](3);
        params[0] = abi.encode(
            IV4Router.ExactInputSingleParams({
                poolKey: key,
                zeroForOne: zeroForOne,
                // forge-lint: disable-next-line(unsafe-typecast) -- corpus amounts are uint128 by construction
                amountIn: uint128(amountIn),
                // forge-lint: disable-next-line(unsafe-typecast) -- as above
                amountOutMinimum: uint128(minAmountOut),
                hookData: ""
            })
        );
        params[1] = abi.encode(currencyIn, amountIn);
        params[2] = abi.encode(currencyOut, minAmountOut);

        bytes[] memory inputs = new bytes[](1);
        inputs[0] = abi.encode(actions, params);

        // `router` takes part in nothing the calldata encodes — it is the destination,
        // not an argument — and is threaded through only so that the signature of this
        // helper reads like the SDK's, which takes it for the same reason.
        router;

        return abi.encodeCall(IUniversalRouter.execute, (abi.encodePacked(V4_SWAP), inputs, deadline));
    }

    /// @dev Every case, byte for byte. A single failure names the case, because the
    /// corpus is chosen so that each one fails for a different reason.
    function test_theSdkEncodesEverySwapTheWayUniswapsOwnTypesDo() public view {
        Corpus memory c = _load();
        assertGt(c.count, 0, "the corpus is empty");
        assertEq(c.names.length, c.count, "the corpus disagrees with its own count");

        for (uint256 i = 0; i < c.count; i++) {
            bytes memory rebuilt = _encode(
                c.router,
                _key(c, i),
                c.zeroForOnes[i],
                vm.parseUint(c.amountIns[i]),
                vm.parseUint(c.minAmountOuts[i]),
                vm.parseUint(c.deadlines[i])
            );

            assertEq(rebuilt, c.calldatas[i], c.names[i]);
        }
    }

    /// @dev The control. Everything above would also pass if this harness and the SDK
    /// were wrong in the same direction about which currency `SETTLE_ALL` names — so
    /// this transposes them and requires the bytes to change. Without it, "the two
    /// agree" would be a claim about two encoders and not about the trade.
    function test_transposingTheSettledCurrenciesChangesTheBytes() public view {
        Corpus memory c = _load();

        for (uint256 i = 0; i < c.count; i++) {
            PoolKey memory key = _key(c, i);
            uint256 amountIn = vm.parseUint(c.amountIns[i]);
            uint256 minAmountOut = vm.parseUint(c.minAmountOuts[i]);
            uint256 deadline = vm.parseUint(c.deadlines[i]);

            bytes memory inverted = _encode(c.router, key, !c.zeroForOnes[i], amountIn, minAmountOut, deadline);

            assertTrue(
                keccak256(inverted) != keccak256(c.calldatas[i]),
                "a swap in the opposite direction encodes identically, so this harness cannot tell buys from sells"
            );
        }
    }
}
