/**
 * Acceptance tests 1, 3 and 6 — that a Program's identity is the identity the chain
 * already gave its markets.
 *
 * Test 1 is the one that matters: it is checked against mainnet, so it fails if this
 * package's notion of identity ever drifts from the engine's. Test 6 covers the shapes
 * mainnet does not yet contain, and is explicitly *not* chain-verified.
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";
import { decodeConfig } from "@verdant/market-engine";
import type { CanonicalConfig } from "@verdant/market-engine";

import { deriveProgramIdentity } from "./identity.js";
import mainnet from "./fixtures/mainnet-engine-markets.json" with { type: "json" };
import vectorIndex from "../../market-engine/vectors/index.json" with { type: "json" };

/**
 * Symbols and decimals are outside the commitment, so any values round-trip.
 *
 * Deliberately wrong ones, in fact. `configHash` is taken over the economics alone, and a
 * test that supplied each market's real symbol could pass while the labels were quietly
 * inside the hash. These cannot.
 */
const IRRELEVANT_LABELS = {
  launchedTokenSymbol: "LABELS-ARE-NOT-ECONOMICS",
  quoteAssetSymbol: "NOR-IS-THIS",
  quoteAssetDecimals: 18,
} as const;

describe("acceptance test 1: identity matches live mainnet markets (chain-verified)", () => {
  /*
   * Only two engine-1 markets exist on Robinhood Chain mainnet. The milestone asked for
   * three; the registry at 0x71a284dd…99eE answers `count() == 2`, so two is every market
   * there is rather than a sample. See docs/v4fun/INVENTORY.md.
   */
  it("has exactly the two markets that exist on chain", () => {
    expect(mainnet.markets).toHaveLength(2);
    expect(mainnet.registryCount).toBe(2);
  });

  for (const market of mainnet.markets) {
    it(`market ${String(market.marketIndex)} (${market.symbol}) derives its on-chain configHash`, () => {
      const config = decodeConfig(market.encodedConfig as `0x${string}`, IRRELEVANT_LABELS);
      const identity = deriveProgramIdentity(config);

      expect(identity.configHash).toBe(market.configHash);
      expect(identity.schemaVersion).toBe(market.engineVersion);
    });
  }

  it("gives the two markets distinct identities", () => {
    const [first, second] = mainnet.markets;
    expect(first).toBeDefined();
    expect(second).toBeDefined();
    expect(first?.configHash).not.toBe(second?.configHash);
  });
});

describe("acceptance test 6: identity matches the committed vectors (vector-based, NOT chain-verified)", () => {
  /*
   * `packages/market-engine/vectors` is generated by `vectors:emit` and hashed against an
   * engine identity pinned in that script — 0x…c0de, which is not a deployed contract. So
   * these agree with the engine's encoder, not with any chain. They are here because they
   * cover seventeen configuration shapes that mainnet's two markets do not: volume ladders,
   * exclusive tiers, whale discounts, four-way distributions and an equity-quoted market.
   */
  const vectors = loadVectors();

  it("loads every vector the index declares", () => {
    expect(vectors).toHaveLength(vectorIndex.count);
  });

  for (const vector of vectors) {
    it(`"${vector.name}" derives the configHash the engine recorded`, () => {
      const config = decodeConfig(vector.encoded, IRRELEVANT_LABELS);
      expect(deriveProgramIdentity(config).configHash).toBe(vector.configHash);
    });
  }
});

describe("acceptance test 3: one differing parameter is a different Program", () => {
  const base = decodeConfig(
    mainnet.markets[0]?.encodedConfig as `0x${string}`,
    IRRELEVANT_LABELS,
  );

  /**
   * One mutation per economically meaningful field, each the smallest one expressible.
   *
   * A single-unit change rather than a dramatic one, because the failure this guards
   * against is a normalizer that rounds or truncates: a hash that survives ±1 ppm is a
   * hash that would let two genuinely different markets share a Program.
   */
  const mutations: readonly (readonly [string, CanonicalConfig])[] = [
    ["buy fee, by one ppm", withStages(base, (stage) => ({ ...stage, buyFeePpm: stage.buyFeePpm + 1 }))],
    ["sell fee, by one ppm", withStages(base, (stage) => ({ ...stage, sellFeePpm: stage.sellFeePpm + 1 }))],
    [
      "stage threshold, by one unit",
      { ...base, stages: [...base.stages.slice(0, -1), bumpThreshold(base)] },
    ],
    ["reference supply, by one unit", { ...base, referenceSupply: base.referenceSupply + 1n }],
    ["fee currency", { ...base, feeCurrency: base.feeCurrency === "QUOTE" ? "TOKEN" : "QUOTE" }],
    ["quote asset", { ...base, quoteAsset: { ...base.quoteAsset, address: ONE_ADDRESS } }],
    [
      "a distribution share",
      {
        ...base,
        distribution: base.distribution.map((share, index) =>
          index === 0 ? { ...share, sharePpm: share.sharePpm - 1 } : share,
        ),
      },
    ],
    ["the buy ceiling", { ...base, maxBuyTokens: (base.maxBuyTokens ?? 0n) + 1n }],
    ["the sell ceiling", { ...base, maxSellTokens: (base.maxSellTokens ?? 0n) + 1n }],
    ["a buy tier appearing", { ...base, buyTiers: [{ thresholdTokens: 1n, feePpm: 1 }] }],
    ["the engine version", { ...base, engineVersion: 2 }],
  ];

  const baseHash = deriveProgramIdentity(base).configHash;

  for (const [what, mutated] of mutations) {
    it(`changing ${what} changes the identity`, () => {
      expect(deriveProgramIdentity(mutated).configHash).not.toBe(baseHash);
    });
  }

  it("gives every mutation a distinct identity from every other", () => {
    const hashes = new Set([
      baseHash,
      ...mutations.map(([, config]) => deriveProgramIdentity(config).configHash),
    ]);
    expect(hashes.size).toBe(mutations.length + 1);
  });
});

describe("labels are outside the identity", () => {
  const encoded = mainnet.markets[0]?.encodedConfig as `0x${string}`;

  it("two decodings with different labels are the same Program", () => {
    const left = decodeConfig(encoded, IRRELEVANT_LABELS);
    const right = decodeConfig(encoded, {
      launchedTokenSymbol: "SOMETHING-ELSE",
      quoteAssetSymbol: "AND-ANOTHER",
      quoteAssetDecimals: 6,
    });

    expect(deriveProgramIdentity(left).configHash).toBe(deriveProgramIdentity(right).configHash);
  });
});

const ONE_ADDRESS = "0x0000000000000000000000000000000000000001" as const;

function withStages(
  config: CanonicalConfig,
  change: (stage: CanonicalConfig["stages"][number]) => CanonicalConfig["stages"][number],
): CanonicalConfig {
  return { ...config, stages: config.stages.map(change) };
}

/** The last stage's threshold, moved by one. Stage 0's threshold is always 0 by definition. */
function bumpThreshold(config: CanonicalConfig): CanonicalConfig["stages"][number] {
  const last = config.stages.at(-1);
  if (last === undefined) throw new Error("a canonical config always has at least one stage");
  return { ...last, threshold: last.threshold + 1n };
}

interface Vector {
  readonly name: string;
  readonly encoded: `0x${string}`;
  readonly configHash: `0x${string}`;
}

/**
 * The vector files, read through the index rather than by globbing the directory.
 *
 * The index declares how many there should be, so a missing vector is a failure rather
 * than a suite that quietly checks fewer cases than it claims to.
 */
function loadVectors(): readonly Vector[] {
  const directory = join(dirname(fileURLToPath(import.meta.url)), "../../market-engine/vectors");

  return vectorIndex.names.map((name, position) => {
    const file = `${String(position).padStart(2, "0")}.json`;
    const vector = JSON.parse(readFileSync(join(directory, file), "utf8")) as Vector;
    if (vector.name !== name) {
      throw new Error(`${file} is "${vector.name}" but the index calls position ${String(position)} "${name}"`);
    }
    return vector;
  });
}
