// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @title AgenDeployer
/// @notice Puts generated bytecode at a deterministic address, and does nothing else.
///
/// @dev This contract deploys arbitrary creation code, and that deserves a straight
/// answer rather than a hedge, because it is the one design decision in the Agen
/// deployment path that cannot be softened.
///
/// A generated market *is* arbitrary bytecode. That is the product. A deployer that
/// accepted only a fixed set of creation codes — the shape `VerdantDeployer` takes,
/// and correctly, for a protocol whose four artefacts are known at compile time —
/// would be a deployer that can only ship markets somebody anticipated, which is the
/// template system Agen exists not to be. So the question is not whether to deploy
/// unknown code. It is where the safety comes from instead.
///
/// It comes from three places, none of them here:
///
/// 1. **Off-chain gates.** Nothing reaches this contract until it has compiled, passed
///    static analysis of its parsed AST, satisfied its own claimed invariants under a
///    fuzzer, and been reviewed as English by the person launching it. Those checks
///    live in the market-compiler package; this is the last step of a pipeline, not
///    the first.
/// 2. **Deployment grants nothing.** A contract deployed here holds no privilege by
///    virtue of having been deployed here. It cannot call back into the factory, it is
///    not trusted by the registry, no allowance is extended to it, and no existing
///    Verdant market can be affected by it. The worst a malicious bundle can do is be
///    a bad market that only its own traders touch.
/// 3. **The address is a commitment.** CREATE2 with a caller-supplied salt means the
///    address is a function of the code, so the bytecode at a published address is the
///    bytecode that was reviewed. A deployer using CREATE would break that link and
///    with it every claim the manifest makes.
///
/// What this contract does enforce is who may call it. Only the factory, fixed at
/// construction. Not because a stray deployment would be dangerous — it would be inert
/// — but because addresses derived from Agen's deployer are addresses people read as
/// Agen's, and provenance that anyone can mint is not provenance.
///
/// Kept separate from the factory for the same reason `VerdantDeployer` is: this needs
/// assembly to deploy code it does not know at compile time, and isolating the one
/// contract that does raw `create2` into forty lines with no other responsibility is
/// what makes that assembly reviewable.
contract AgenDeployer {
    /// @notice The only address that may deploy.
    /// @dev Immutable. The cycle with the factory — which needs this address in turn —
    /// is broken by deployment order: this is deployed first naming the factory's
    /// predicted address, and the factory's constructor asserts the prediction held.
    address public immutable factory;

    error NotFactory(address caller);
    error DeploymentFailed(bytes32 salt);
    error AlreadyDeployed(address target);
    error EmptyInitCode();

    event Deployed(address indexed deployed, bytes32 indexed salt, bytes32 initCodeHash);

    constructor(address factory_) {
        factory = factory_;
    }

    /// @notice Deploy `initCode` at the CREATE2 address for `salt`.
    /// @param salt The caller's salt. For hooks this is the mined one, and the address
    /// it produces is the whole point of having mined it.
    /// @param initCode Creation code with constructor arguments already appended.
    /// @return deployed The address the code now lives at.
    ///
    /// @dev Returns rather than asserts the address: the factory compares it against
    /// what the manifest predicted, and that comparison belongs where the manifest is.
    /// Splitting it that way means this contract has no opinion about what is being
    /// deployed, which is what keeps it forty lines.
    function deploy(bytes32 salt, bytes calldata initCode) external returns (address deployed) {
        if (msg.sender != factory) revert NotFactory(msg.sender);
        if (initCode.length == 0) revert EmptyInitCode();

        bytes32 initCodeHash = keccak256(initCode);
        address target = computeAddress(salt, initCodeHash);

        // CREATE2 to an occupied address fails silently in some clients and reverts in
        // others; checking first turns both into one legible error. It also catches the
        // replay case — the same bundle deployed twice — before any gas is spent on it.
        if (target.code.length != 0) revert AlreadyDeployed(target);

        bytes memory code = initCode;
        assembly ("memory-safe") {
            deployed := create2(0, add(code, 0x20), mload(code), salt)
        }

        // A constructor that reverts, or code that exceeds the size limit, returns the
        // zero address here rather than bubbling anything useful up.
        if (deployed == address(0)) revert DeploymentFailed(salt);

        emit Deployed(deployed, salt, initCodeHash);
    }

    /// @notice Where `initCodeHash` under `salt` will land.
    /// @dev Public because the whole deployment plan is computed off-chain before
    /// anything is sent, and an interface showing a creator their market's addresses
    /// before they sign should be reading them from the same arithmetic the chain will.
    function computeAddress(bytes32 salt, bytes32 initCodeHash) public view returns (address) {
        return address(uint160(uint256(keccak256(abi.encodePacked(bytes1(0xff), address(this), salt, initCodeHash)))));
    }
}
