import {
  LAUNCH_MODELS,
  LAUNCH_MODEL_ORDER,
  LAUNCH_MODEL_STATUS_LABELS,
  type LaunchModelDefinition,
} from "@verdant/config";
import type { Metadata } from "next";
import Image, { type StaticImageData } from "next/image";
import Link from "next/link";

import { LaunchSoon } from "../../components/launch-soon";
import { Badge, PageHeading } from "../../components/primitives";
import { Reveal } from "../../components/reveal";
import { LAUNCHING_OPEN } from "../../lib/launch-window";
import classicArt from "../../../public/models/classic.jpg";
import evergreenArt from "../../../public/models/evergreen.jpg";
import stockPairedArt from "../../../public/models/stock-paired.jpg";

export const metadata: Metadata = {
  title: "Choose a launch model",
  description:
    "Pair a fixed-supply token against ether or a tokenized equity, with the fee written into the pool at creation.",
};

/**
 * The model chooser.
 *
 * A creator's first decision is what their market is quoted in, because it is the one
 * decision that cannot be revisited afterwards — it is part of the pool's identity, and a
 * pool cannot be repriced against a different asset later. So it is a page of its own,
 * before any form, rather than a dropdown inside one.
 *
 * A model that is not ready is shown rather than hidden, and its badge and its button say
 * so — Evergreen offers the design to read rather than a form to fill. What remains to be
 * built is not itemised on the card: three cards a screen tall are harder to compare than
 * three short ones, and a chooser is for choosing. The roadmap lives on `/docs/models`,
 * where somebody who wants it is already looking for it.
 */
export default function LaunchPage() {
  /*
   * The chooser is not shown while there is nothing to choose. It would be a page of three
   * cards whose every button leads to the same notice, which is a worse way of saying the
   * one thing this page currently has to say.
   */
  if (!LAUNCHING_OPEN) {
    return (
      <div className="px-6 py-24">
        <LaunchSoon />
      </div>
    );
  }

  return (
    <div className="pb-10">
      <section className="px-6 pb-14 pt-20">
        <PageHeading
          eyebrow={<Badge tone="accent">Step 1 of 2</Badge>}
          title="Choose a launch model"
          lede="A model decides what your token is priced against, how the fee is charged and who can ever touch the launch position. Everything it fixes is fixed at creation."
        />
      </section>

      <div className="mx-auto grid max-w-6xl gap-6 px-6 lg:grid-cols-3">
        {LAUNCH_MODEL_ORDER.map((id, index) => (
          <Reveal key={id} delay={index * 90} className="flex">
            <ModelCard model={LAUNCH_MODELS[id]} index={index} />
          </Reveal>
        ))}
      </div>

      <Reveal as="div" className="mx-auto mt-14 max-w-3xl px-6">
        <div className="hairline" />
        <h2 className="mt-10 text-center text-[1.35rem] font-semibold tracking-tight text-ink">
          What every model does, regardless of which you pick
        </h2>
        <dl className="mt-8 grid gap-x-10 gap-y-6 sm:grid-cols-2">
          {[
            [
              "Supply is minted once",
              "There is no mint function, no owner and no upgrade path. The number that exists at launch is the number that will ever exist.",
            ],
            [
              "The fee cannot be edited",
              "It is written into the hook at creation. Not by the creator, not by Verdant, not by a governance vote.",
            ],
            [
              "The launch position is locked",
              "It is transferred to a locker with no operator and no early-release path. Fees can be collected from it; liquidity cannot be pulled out of it.",
            ],
            [
              "Fee recipients are fixed",
              "Where fee revenue goes is decided at creation and cannot be redirected afterwards by anyone.",
            ],
          ].map(([title, body]) => (
            <div key={title}>
              <dt className="text-[0.9rem] font-semibold text-ink">{title}</dt>
              <dd className="mt-1.5 text-[0.82rem] leading-relaxed text-ink-muted">{body}</dd>
            </div>
          ))}
        </dl>
      </Reveal>
    </div>
  );
}

/**
 * Art per model: a photograph, over the gradient that used to be the whole of it.
 *
 * The gradient stays underneath rather than being deleted, and it earns its place twice. It
 * is what the card is painted with in the moment before a 40 to 80 KB JPEG decodes, in the
 * hue the photograph turns out to be, so the head of the card does not flash. And it is
 * still there if a picture is ever missing, which makes the art an improvement to this page
 * rather than a thing the page now depends on.
 *
 * Generated by `pnpm --filter @verdant/landing brand` from the originals in `brand-source/`,
 * which are 15 to 26 MB each. Imported rather than referenced by path so that Next reads
 * their real dimensions at build time and can serve a size that suits the display.
 */
const ART: Record<string, { readonly image: StaticImageData; readonly beneath: string }> = {
  classic: {
    image: classicArt,
    beneath:
      "linear-gradient(150deg, oklch(0.4 0.09 158), oklch(0.32 0.08 196) 55%, oklch(0.36 0.06 96))",
  },
  "stock-paired": {
    image: stockPairedArt,
    beneath:
      "linear-gradient(150deg, oklch(0.36 0.09 254), oklch(0.32 0.09 300) 55%, oklch(0.38 0.06 20))",
  },
  evergreen: {
    image: evergreenArt,
    beneath:
      "linear-gradient(150deg, oklch(0.38 0.07 140), oklch(0.31 0.08 165) 55%, oklch(0.36 0.05 110))",
  },
};

function ModelCard({
  model,
  index,
}: {
  readonly model: LaunchModelDefinition;
  readonly index: number;
}) {
  const openable = model.status !== "design";
  const art = ART[model.id];

  return (
    <article className="group flex flex-col overflow-hidden rounded-panel border border-border bg-surface shadow-card backdrop-blur-xl transition duration-200 hover:-translate-y-0.5 hover:shadow-lift">
      <div
        className="relative h-40 overflow-hidden border-b border-border"
        style={{ backgroundImage: art?.beneath }}
      >
        {art === undefined ? null : (
          <Image
            src={art.image}
            alt=""
            fill
            sizes="(min-width: 1024px) 33vw, 100vw"
            className="object-cover transition-transform duration-500 group-hover:scale-[1.03]"
            // Three of these are the first thing on the page, so they are not lazy: a card
            // whose art arrives after the scroll has already passed it may as well not have
            // any.
            priority={index === 0}
          />
        )}

        {/* Enough shade at the top for the badge to be legible over a photograph that has
            its own ideas about where the light regions are, and a little at the bottom so
            the picture meets the card's own surface rather than butting against it. */}
        <div className="absolute inset-0 bg-gradient-to-b from-canvas/60 via-canvas/5 to-canvas/40" />

        <div className="absolute left-4 top-4">
          <Badge tone={model.status === "ready" ? "ink" : "neutral"}>
            {LAUNCH_MODEL_STATUS_LABELS[model.status]}
          </Badge>
        </div>
      </div>

      <div className="flex flex-1 flex-col p-6">
        <h2 className="text-[1.2rem] font-semibold tracking-tight text-ink">{model.label}</h2>
        <p className="mt-2 text-[0.85rem] leading-relaxed text-ink-muted">{model.summary}</p>

        <dl className="mt-5 space-y-2 border-t border-border pt-4 text-[0.78rem]">
          <div className="flex justify-between gap-3">
            <dt className="text-ink-muted">Quoted in</dt>
            <dd className="text-right text-ink">{model.pair}</dd>
          </div>
          <div className="flex justify-between gap-3">
            <dt className="text-ink-muted">You earn in</dt>
            <dd className="text-right text-ink">{model.rewardCurrency}</dd>
          </div>
        </dl>

        <ul className="mt-4 space-y-1.5">
          {model.highlights.map((highlight) => (
            <li key={highlight} className="flex gap-2 text-[0.8rem] leading-relaxed text-ink-muted">
              <span aria-hidden="true" className="mt-1.5 size-1 shrink-0 rounded-full bg-accent" />
              {highlight}
            </li>
          ))}
        </ul>

        <div className="mt-6 flex-1" />

        {openable ? (
          <Link
            href={`/launch/${model.id}`}
            className="inline-flex h-11 items-center justify-center rounded-full bg-ink px-6 text-[0.9rem] font-medium text-ink-inverse transition hover:bg-ink/90 active:scale-[0.985]"
          >
            {model.status === "ready" ? "Launch" : "Open the form"}
          </Link>
        ) : (
          <Link
            href="/docs/models"
            className="inline-flex h-11 items-center justify-center rounded-full border border-border bg-surface px-6 text-[0.9rem] font-medium text-ink-muted transition hover:border-border-strong hover:bg-surface-raised hover:text-ink"
          >
            Read the design
          </Link>
        )}
      </div>
    </article>
  );
}
