/**
 * The migration, and its reverse.
 *
 * The SQL is read from `drizzle/` rather than embedded as strings here, so there is one copy of
 * it: the forward file is generated by `drizzle-kit generate` from `schema.ts` and is what would
 * run in production, and a copy inlined in TypeScript would be a second version that drifts the
 * first time the schema changes and only one of them is regenerated.
 *
 * Reading a file makes this module impure, which is why it is here and not in
 * `@verdant/registry`. That package has no filesystem access at all, asserted by its own tests.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

/**
 * The tables this migration owns.
 *
 * Named here so `migrate.test.ts` can assert the migration creates exactly these and the reverse
 * removes exactly these. Not derived from `schema.ts`: a table present in the schema but missing
 * from the migration is precisely the bug worth catching, and deriving the expectation from the
 * same place as the subject would hide it.
 */
export const PROGRAM_TABLES = [
  "programs",
  "program_versions",
  "program_markets",
  "program_lineage",
] as const;

/**
 * The table the second migration owns.
 *
 * Separate from `PROGRAM_TABLES` rather than appended to it, and the separation is load-bearing in
 * two places. `migrate.test.ts` asserts that migration 0000 creates *exactly* the four Program
 * tables, so a fifth name in that list would fail a passing M1 test for no reason other than
 * bookkeeping. And the two migrations are genuinely independent: 0000 is the registry, 0001 is the
 * record of launches that feed it, and 0001 can be rolled back on its own without touching a single
 * Program row.
 */
export const ATTEMPT_TABLES = ["launch_attempts"] as const;

/** Every table the registry's database holds once both migrations have run. */
export const ALL_TABLES = [...PROGRAM_TABLES, ...ATTEMPT_TABLES] as const;

const PROGRAMS_MIGRATION = "0000_programs";
const ATTEMPTS_MIGRATION = "0001_launch_attempts";

function read(file: string): string {
  return readFileSync(fileURLToPath(new URL(`../drizzle/${file}`, import.meta.url)), "utf8");
}

/**
 * Every migration, in order, read from drizzle-kit's own journal.
 *
 * ## Why this is derived rather than listed
 *
 * Because a list is a thing to forget. Before this existed, each suite set its database up by
 * calling `upSql()` — migration `0000` by name — which was correct exactly once and became a latent
 * defect the moment a second migration existed. It surfaced the way that class of defect always
 * does: not as "the test pins the wrong migration" but as
 * `column "slug" of relation "programs" does not exist`, eight times, in tests that have nothing to
 * do with slugs and whose assertions were entirely correct.
 *
 * The journal is drizzle-kit's record of what it has generated and is written by `generate`, so a
 * migration that exists is in it and one that does not is not. Deriving the order from there means
 * a new migration is applied everywhere without anybody editing a test, which is the property that
 * was missing.
 *
 * The per-migration accessors below stay, because `migrate.test.ts` and `attempts-migrate.test.ts`
 * are *about* one migration each — applying it alone and reversing it alone is their subject rather
 * than their setup. Those are the only two places a migration may be named.
 */
interface JournalEntry {
  readonly idx: number;
  readonly tag: string;
}

function journalTags(): readonly string[] {
  const parsed = JSON.parse(read("meta/_journal.json")) as {
    readonly entries?: readonly JournalEntry[];
  };

  const entries = [...(parsed.entries ?? [])].sort((left, right) => left.idx - right.idx);

  if (entries.length === 0) {
    throw new Error(
      "drizzle's journal lists no migrations, so there is no schema to apply. This is a build " +
        "problem rather than an empty database: the journal is committed alongside the SQL.",
    );
  }

  return entries.map((entry) => entry.tag);
}

/** Every migration's tag, oldest first. */
export const MIGRATION_TAGS: readonly string[] = journalTags();

/** Every forward migration, in the order they must be applied. */
export function allUpSql(): readonly string[] {
  return MIGRATION_TAGS.map((tag) => read(`${tag}.sql`));
}

/** Every reverse migration, newest first, which is the order they must be applied in. */
export function allDownSql(): readonly string[] {
  return [...MIGRATION_TAGS].reverse().map((tag) => read(`${tag}.down.sql`));
}

/** The forward migration, as generated from `schema.ts`. */
export function upSql(): string {
  return read(`${PROGRAMS_MIGRATION}.sql`);
}

/** Its hand-written reverse. See the note at the top of the file it reads. */
export function downSql(): string {
  return read(`${PROGRAMS_MIGRATION}.down.sql`);
}

/** The second migration: `launch_attempts`, as generated from `schema.ts`. */
export function attemptsUpSql(): string {
  return read(`${ATTEMPTS_MIGRATION}.sql`);
}

/** Its hand-written reverse. */
export function attemptsDownSql(): string {
  return read(`${ATTEMPTS_MIGRATION}.down.sql`);
}
