/**
 * The migration, and its reverse.
 *
 * The SQL is read from `drizzle/` rather than embedded as strings here, so there is one copy of
 * it: the forward file is generated by `drizzle-kit generate` from `schema.ts` and is what would
 * run in production, and a copy inlined in TypeScript would be a second version that drifts the
 * first time the schema changes and only one of them is regenerated.
 *
 * Reading a file makes this module impure, which is why it is here and not in
 * `@verdant/registry`. That package has no filesystem access at all, asserted by its own tests.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

/**
 * The tables this migration owns.
 *
 * Named here so `migrate.test.ts` can assert the migration creates exactly these and the reverse
 * removes exactly these. Not derived from `schema.ts`: a table present in the schema but missing
 * from the migration is precisely the bug worth catching, and deriving the expectation from the
 * same place as the subject would hide it.
 */
export const PROGRAM_TABLES = [
  "programs",
  "program_versions",
  "program_markets",
  "program_lineage",
] as const;

const MIGRATION = "0000_programs";

function read(file: string): string {
  return readFileSync(fileURLToPath(new URL(`../drizzle/${file}`, import.meta.url)), "utf8");
}

/** The forward migration, as generated from `schema.ts`. */
export function upSql(): string {
  return read(`${MIGRATION}.sql`);
}

/** Its hand-written reverse. See the note at the top of the file it reads. */
export function downSql(): string {
  return read(`${MIGRATION}.down.sql`);
}
